trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: Source
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run build
          - upload: |
              package.json
              LICENSE.md
              README.md
              dist
      - job: Docs
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run docs
          - upload: docs
            artifact: docs
  # - stage: Deploy
  #   jobs:
  #     - job: Package

### TRAVIS FILE
# language: node_js
# node_js:
#   - "node"
# script:
#   - npm run build
#   - npm run docs
# deploy:
#   - provider: npm
#     email: $NPM_EMAIL
#     api_key: $NPM_AUTH_TOKEN
#     skip_cleanup: true
#     on:
#       branch: master
#   - provider: pages
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     local-dir: docs
#     on:
#       branch: master
