trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: Source
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run build
          - upload: "**/*"
      - job: Docs
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run docs
          - upload: "docs/*"
  # - stage: Deploy
  #   jobs:
  #     - job: Package

