trigger:
  - master
stages:
  - stage: Build
    jobs:
      - job: Source
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run build
          - upload: dist
      - job: Docs
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: npm ci
          - script: npm run docs
          - upload: docs
            artifact: docs
  - stage: Deploy
    # condition: 'and(succeeded(), eq(variables[''Build.SourceBranch''], ''refs/heads/master''))'
    jobs:
      - deployment: Docs
        environment: GitHub
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: GitHub
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: docs
                - script: |
                    git init
                    git config --local user.name "Azure Pipelines"
                    git config --local user.email "azuredevops@microsoft.com"
                    git add .
                    git commit -m "latest docs"
                  workingDirectory: $(Pipeline.Workspace)/docs
                - task: InstallSSHKey@0
                  inputs:
                    knownHostsEntry: $(githubKnownHosts)
                    sshPublicKey: $(githubPublicKey)
                    sshKeySecureFile: rating-scales_gh-pages
                - script: |
                    git remote add origin
                    git@github.com:decsys/rating-scales.git
                    git push origin HEAD:gh-pages -f
                  workingDirectory: $(Pipeline.Workspace)/docs


### TRAVIS FILE
# language: node_js
# node_js:
#   - "node"
# script:
#   - npm run build
#   - npm run docs
# deploy:
#   - provider: npm
#     email: $NPM_EMAIL
#     api_key: $NPM_AUTH_TOKEN
#     skip_cleanup: true
#     on:
#       branch: master
#   - provider: pages
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     local-dir: docs
#     on:
#       branch: master
